id = "mau"
name = "Mau Theme"
version = "0.0.2"
schema_version = 1
authors = ["Mauricio Coelho <mauscoelho@gmail.com>"]
description = "Mau Zed theme"
repository = "https://github.com/mauscoelho/zed-mau-themes"
